Orcid
BIO6032/2022-SEIR-reproduction pull request #13
Opened 2022-03-24 09:49 UTC by Marine1719

Orcid_ID_Marine Hubert 
0000-0002-6054-6895

2022-03-24 14:41 UTC, tpoisot requested changes
Il reste des ORCID manquants

2022-03-24 14:41 UTC, tpoisot commented on metadata.yaml
>    - name: Aude Rebattet
ORCID manquant

2022-03-24 14:41 UTC, tpoisot commented on metadata.yaml
> +  - name: Andi Hanna
ORCID manquant

2022-03-24 14:50 UTC, Campeon-del-Mundo commented on metadata.yaml
> +  - name: Andi Hanna
https://orcid.org/
0000-0001-9543-188X

2022-03-30 00:45 UTC, Campeon-del-Mundo approved these changes

2022-03-31 14:33 UTC, merged